export {DeclinePipe} from './decline.pipe'
export {FirstCapitalPipe} from './first-capital.pipe'
export {FixedPipe} from './fixed.pipe'
export {IncludesPipe} from './includes.pipe'
export {JoinPipe} from './join.pipe'
export {LinkWithProtocolPipe} from './link-with-protocol.pipe'
export {PhonePipe} from './phone.pipe'
export {linkWithProtocol, romanize, declOfNum} from './pipes-utils'
export {PricePipe} from './price.pipe'
export {RomanizePipe} from './romanize.pipe'